[package]
name = "ghostpass-crypto"
version = "0.0.0"
edition.workspace = true
license.workspace = true
publish = false
description = "Cœur cryptographique zero-knowledge de GhostPass"

[dependencies]
argon2 = "0.5.3"
base64 = "0.22.1"
chacha20poly1305 = "0.10.1"
crypto_box = { version = "0.9.1", features = ["seal", "chacha20"] }
hkdf = "0.13.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
sha2 = "0.11.0"
thiserror = "2.0.18"
zeroize = "1.9.0"

[dev-dependencies]
